### ISSUE TITLE
Building on windows, tutorial and suggestions

### ISSUE THREAD

**Issue by waynenilsen** [alexcrichton/curl-rust#111] opened 2016-06-01 19:49 UTC
I am happy to help by writing out the details in markdown somewhere but I think this issue of building this crate on windows should be addressed. Currently, on a standard version of windows without linux tools installed such as `sh`, this build will fail. This came up when I was trying to install [cargo-edit](https://github.com/killercup/cargo-edit) on windows via `cargo install cargo-edit` which is one of my favorite linux programs for working with rust. I did receive the useful message "is `sh` not installed?" but it was perhaps a bit too short. Sadly, in version 0.2.18 that is used by cargo-edit, this message did not appear. I found the message by cloning this repo and trying to build. I still do not know the best way forward. Is MinGW expected? Something else?

Thanks for the advice. I think whatever information is included in the answer should in some way probably be added to the readme.

**Comment by alexcrichton** [comment] 2016-06-02 06:17
Yeah unfortunately building this crate for the x86_64-pc-windows-gnu target requires building it in a MSYS environment (as do almost all other C projects). If you build for x86_64-pc-windows-msvc, however, it should in theory work so long as VS is installed.

I'd be more than ok updating the docs, here, though! I know this tends to be a pain point with Windows unfortunately :(

**Comment by waynenilsen** [comment] 2016-06-02 19:15
I installed msys via MinGW but `cargo build` seems to be hung. I'm going to let it run overnight just to be sure.

**Comment by waynenilsen** [comment] 2016-06-03 14:24
Yes, it turns out that `cargo build` hung with MSYS environment installed.

**Comment by alexcrichton** [comment] 2016-06-05 06:43
Weird! I vaguely remember running into that but I don't remember figuring out why. Can you take a look and see which processes are hung?

**Comment by waynenilsen** [comment] 2016-06-05 13:14
The best that I could tell it was hung on make but not sure what within make was hung up.. I will try again when I get back to the machine tomorrow

**Comment by waynenilsen** [comment] 2016-06-06 12:20
I ran again this morning and got `checking size of void*... 0 configure: error: cannot find out size of void*.` So I did some googling around and found out that maybe it wants `vcvars` so I ran that. It does seem to be running `gcc` now which is a good sign.

**Comment by alexcrichton** [comment] 2016-06-06 14:22
Hm vcvars should only be necessary for MSVC targets which don't use gcc, so that's odd! I've found the configure script to take forever on Windows, but an hour is certainly a bit excessive... Can you get a dump of the process running to see where it's at?

**Comment by waynenilsen** [comment] 2016-06-06 14:56
`make` is still pinning a core. Not sure what you mean about "get a dump of the process running" how would I go about doing that? Some tool?

**Comment by waynenilsen** [comment] 2016-06-06 16:14
It seems (I didn't notice any error messages) that I was able to successfully run `sh configure` then `make` from the `curl-sys\curl` directory. I saw that you had some extra flags in your `build.rs` file but I did not go through the logic and figure out exactly which flags to use.

**Comment by alexcrichton** [comment] 2016-06-07 06:40
yeah sometimes calling shell scripts from Rust is subtly different than calling them from the shell itself, and I've never really quite figured out what the problem is...

**Comment by mitsuhiko** [comment] 2016-07-19 06:24
I think one thing that should be documented is that it only builds with VS2015 or later.

**Comment by alexcrichton** [comment] 2016-07-19 15:40
@mitsuhiko oh dear that's not good! It's certainly intended to build with more than that, do you have a copy of the error on previous versions?

**Comment by mitsuhiko** [comment] 2016-07-21 20:27
@alexcrichton i'm travelling without windows machine right now and probably won't be at my desktop for a month. I think it complained about undefined symbols from libc. I tried with I believe 2013 before that.

**Comment by alexcrichton** [comment] 2016-07-22 20:45
@mitsuhiko I've now merged https://github.com/alexcrichton/curl-rust/pull/119 which I *think* uses VS 2013, but it seems to work?

**Comment by blakehawkins** [comment] 2016-08-20 23:32
Hi,

On a fresh install of msys2 (windows with -gnu toolchain), building this package has abysmally poor debug info - e.g. https://gist.github.com/anonymous/eb7c2e4904687b374154f19e14d6eda5

I found out that you need to be able to build libcurl from source for this package to build. By building libcurl from source (which has better debug info) I managed to make a list of necessary packages:

```
autoconf
git
libcurl-devel
libcurl
man
curl
vim
binutils
gcc
make
automake
libtool
pkg-config
```

Hopefully nothing is missing.

**Comment by alexcrichton** [comment] 2019-09-09 15:36
I'm going to close this since I don't think this is as relevant now as it used to be.

**Closed by alexcrichton** 2019-09-09 15:36 UTC
