### ISSUE TITLE
Fails to build on windows 10

### ISSUE THREAD

**Issue by yorodm** [alexcrichton/curl-rust#228] opened 2018-09-19 14:36 UTC
I'm building a project that depends on `curl-sys v0.2.5` using `rustc 1.30.0-nightly` and this is what I get:

error: failed to run custom build command for `curl-sys v0.2.5`
process didn't exit successfully: `C:\Users\hp\AppData\Local\Temp\cargo-installMAEooA\release\build\curl-sys-7779715931098c88\build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=C:\Users\hp\AppData\Local\Temp\cargo-installMAEooA\release\build\curl-sys-a4be539c580cc90d\out/lib
cargo:rustc-link-lib=static=curl
cargo:root=C:\Users\hp\AppData\Local\Temp\cargo-installMAEooA\release\build\curl-sys-a4be539c580cc90d\out
cargo:include=C:\Users\hp\AppData\Local\Temp\cargo-installMAEooA\release\build\curl-sys-a4be539c580cc90d\out/include
cargo:rustc-link-lib=ws2_32
cargo:rustc-link-lib=crypt32

--- stderr
fatal: not a git repository (or any of the parent directories): .git
thread 'main' panicked at 'fs::hard_link(inc.join("lib/zlib.lib"), inc.join("lib/zlib_a.lib")) return the error O sistema não conseguiu localizar o ficheiro especificado. (os error 2)', C:\Users\hp\.cargo\registry\src\-bf9bcbf58c2fe7c7\curl-sys-0.2.5\build.rs:254:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `libssh2-sys v0.1.41`
process didn't exit successfully: `C:\Users\hp\AppData\Local\Temp\cargo-installMAEooA\release\build\libssh2-sys-cd902b2c8e879d89\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\hp\\.cargo\\registry\\src\\-bf9bcbf58c2fe7c7\\libssh2-sys-0.1.41\\libssh2" "-G" "Visual Studio 14 2015 Win64" "-Thost=x64" "-DCRYPTO_BACKEND=WinCNG" "-DZLIB_INCLUDE_DIR=C:\\Users\\hp\\AppData\\Local\\Temp\\cargo-installMAEooA\\release\\build\\libz-sys-54a5bf97816ce366\\out/include" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\hp\\AppData\\Local\\Temp\\cargo-installMAEooA\\release\\build\\libssh2-sys-e1943adedbfb4929\\out" "-DCMAKE_C_FLAGS= /nologo /MD" "-DCMAKE_C_FLAGS_RELEASE= /nologo /MD" "-DCMAKE_CXX_FLAGS= /nologo /MD" "-DCMAKE_CXX_FLAGS_RELEASE= /nologo /MD" "-DCMAKE_BUILD_TYPE=Release"
-- Selecting Windows SDK version  to target Windows 10.0.14393.
-- The C compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include files windows.h, bcrypt.h
-- Looking for include files windows.h, bcrypt.h - found
-- Looking for include file ntdef.h
-- Looking for include file ntdef.h - not found
-- Looking for include file ntstatus.h
-- Looking for include file ntstatus.h - found
-- Looking for include files windows.h, wincrypt.h
-- Looking for include files windows.h, wincrypt.h - found
-- Configuring incomplete, errors occurred!
See also "C:/Users/hp/AppData/Local/Temp/cargo-installMAEooA/release/build/libssh2-sys-e1943adedbfb4929/out/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/hp/AppData/Local/Temp/cargo-installMAEooA/release/build/libssh2-sys-e1943adedbfb4929/out/build/CMakeFiles/CMakeError.log".

--- stderr
fatal: not a git repository (or any of the parent directories): .git
CMake Error at C:/Users/hp/Documents/executable/cmake-3.12.2-win64-x64/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
Call Stack (most recent call first):
  C:/Users/hp/Documents/executable/cmake-3.12.2-win64-x64/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Users/hp/Documents/executable/cmake-3.12.2-win64-x64/share/cmake-3.12/Modules/FindZLIB.cmake:112 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:219 (find_package)

thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\hp\.cargo\registry\src\-bf9bcbf58c2fe7c7\cmake-0.1.34\src\lib.rs:776:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

I'm using `cmake version 3.12.2` and Visual Studio 2015 build tools

**Comment by alexcrichton** [comment] 2018-09-19 18:12
Thanks for the report! Can you be sure to update all versions of the crates involved? The most recent version of this crate does not use cmake.

**Comment by yorodm** [comment] 2018-09-19 21:56
Thanks, I will create an issue in the [cargo-template](https://github.com/pwoolcoc/cargo-template/) to ask them to update their references

**Comment by alexcrichton** [comment] 2018-09-20 00:02
Ok! In the meantime I'm gonna close this as I believe the issue is fixed, but let me know if an update doesn't fix it!

**Closed by alexcrichton** 2018-09-20 00:02 UTC
