### ISSUE TITLE
Latest version causes Multi::wait to block and ignore socket events

### ISSUE THREAD

**Issue by sagebind** [alexcrichton/curl-rust#227] opened 2018-09-14 02:51 UTC
Since commit 7f0f5dad2458313e2800cf915c55f180184f6617, using `Multi::wait()` together with `Multi::get_timeout()` produces very strange results when combined with one or more extra `WaitFd`s passed to `wait()`.

I'm seeing two strange behaviors:

**First scenario**: When `get_timeout()` returns `Ok(None)`, my understanding is that curl doesn't have enough info to specify an appropriate timeout value and I should pick a reasonable default. I pick 1s in this case.

When this happens, for some reason, calling `wait()` with the default timeout causes curl to block forever until the given timeout is reached, even if there is socket activity on one or more easy handles, or on an extra fd.

Below is an example program that reproduces the problem:

```rust
extern crate curl;

struct Handler;

impl curl::easy::Handler for Handler {}

fn main() -> Result<(), Box<std::error::Error>> {
    let mut easy = curl::easy::Easy2::new(Handler);
    easy.verbose(true)?;
    easy.get(true)?;
    easy.url("http://example.org")?;

    let multi = curl::multi::Multi::new();
    let _easy = multi.add2(easy)?;

    let mut extra_fds = [curl::multi::WaitFd::new()];
    extra_fds[0].set_fd(0);
    extra_fds[0].poll_on_read(true);

    while multi.perform()? > 0 {
        let timeout = multi.get_timeout()?.unwrap_or(std::time::Duration::from_secs(100));
        println!("timeout: {:?}", timeout);
        multi.wait(&mut extra_fds, timeout)?;
    }

    Ok(())
}
```

**Second scenario**: In this scenario, curl _does_ return a recommended timeout, but is a very large number, such as 300 seconds. Normally this would be fine, but similar to the first scenario, curl blocks for the full timeout duration, even when there is socket activity that should interrupt it.

I'm still working on extracting an example from my code that reproduces this.

I'm not sure if upgrading the version of curl being used caused this problem and it is an upstream bug, or changing how curl is compiled introduced this issue. I've done some digging myself, but hopefully someone else with more knowledge might have a better idea of the cause.

My unproven theory is that somehow the latest change causes curl to use a really poor implementation for `curl_multi_wait()`.

Tested on Linux.

**Comment by alexcrichton** [comment] 2018-09-14 16:41
Oh dear this sounds bad, thanks for the report! I tried digging in a bit last night but couldn't turn up much unfortunately. I'll play around today with switching submodules and see if this is a bug in the update or the build system changes.

**Comment by sagebind** [comment] 2018-09-14 16:56
Interesting to note: it seems like this behavior only happens if DNA resolution is required. When connecting to an IP address, it seems like the problem goes away. I haven't confirmed this, but I wonder if the flags changed which DNS resolved is being used.

**Comment by alexcrichton** [comment] 2018-09-14 18:05
Ok I believe I've now confirmed that the behavior of the program above changed in https://github.com/alexcrichton/curl-rust/commit/85d59946bcc53f68d7cfcd32f80fd7da50ee0b01, so I think it's due to that curl submodule update?

**Comment by sagebind** [comment] 2018-09-15 04:57
I did some further investigation tonight, this time armed with LLDB (stepping between Rust and C is magical!). Still no answers, but I think I have a grasp as to what behavior precisely has changed.

When calling `perform()`, while the easy handle is in a `WAITRESOLVE` state, the handle expiration timer is being set to the value of `CURLOPT_CONNECTTIMEOUT_MS`, which is in turn returned by `get_timeout()`. After a couple of iterations of perform and wait, the hostname gets resolved and the state transitions to `WAITCONNECT`. Once this happens, `get_timeout()` begins to return more reasonable timeouts and things begin to work properly.

Previously it would seem that `get_timeout()` would return either 0 or a small value like 1ms while the easy handle is in the `WAITRESOLVE` state.

I don't have any more time available to researching this bug, so I've employed a workaround for the time being. Here it is: when `get_timeout()` returns a duration that matches exactly the value of `CURLOPT_CONNECTTIMEOUT_MS`, treat it as likely to be this bug and truncate the timeout to a very small value.

I am now confident this is an upstream curl bug; the fact that revving the curl submodule causes this is good evidence. I will open an issue there and link it back here.

**Comment by sagebind** [comment] 2018-09-18 14:05
@alexcrichton Looks like the libcurl fix is on `master` now; updating the curl submodule should resolve the issue here.

**Comment by alexcrichton** [comment] 2018-09-18 16:27
Ok great! I actually updated to the master branch yesterday for other reasons, want to check out the most recently published version and see if it works?

**Comment by sagebind** [comment] 2018-09-18 17:40
Yep, already did. I cloned this repo, updated the submodule locally, and ran my problematic example against that, and it worked.

**Comment by alexcrichton** [comment] 2018-09-18 17:51
Oh sorry I mean the version of `curl-sys` published on crates.io which I believe should have all the support necessary now.

**Comment by sagebind** [comment] 2018-09-18 17:56
Ah I misunderstood; I will try that and verify it.

**Comment by sagebind** [comment] 2018-09-19 02:40
Nope, looks like the most recent `curl-sys` doesn't include commit https://github.com/curl/curl/commit/ec5d0991ccf1e04fc384b312fc1b24c21259c0f1.

**Comment by alexcrichton** [comment] 2018-09-19 18:40
Oops wow that is quite recent, should be fixed and published now!

**Closed by alexcrichton** 2018-09-19 18:40 UTC
